let routes = { 
    'passport.authorizations.authorize': 'http://localhost/oauth/authorize', 
    'passport.authorizations.approve': 'http://localhost/oauth/authorize', 
    'passport.authorizations.deny': 'http://localhost/oauth/authorize', 
    'passport.token': 'http://localhost/oauth/token', 
    'passport.tokens.index': 'http://localhost/oauth/tokens', 
    'passport.tokens.destroy': 'http://localhost/oauth/tokens/{token_id}', 
    'passport.token.refresh': 'http://localhost/oauth/token/refresh', 
    'passport.clients.index': 'http://localhost/oauth/clients', 
    'passport.clients.store': 'http://localhost/oauth/clients', 
    'passport.clients.update': 'http://localhost/oauth/clients/{client_id}', 
    'passport.clients.destroy': 'http://localhost/oauth/clients/{client_id}', 
    'passport.scopes.index': 'http://localhost/oauth/scopes', 
    'passport.personal.tokens.index': 'http://localhost/oauth/personal-access-tokens', 
    'passport.personal.tokens.store': 'http://localhost/oauth/personal-access-tokens', 
    'passport.personal.tokens.destroy': 'http://localhost/oauth/personal-access-tokens/{token_id}', 
    'flyers.add_photo': 'http://localhost/api/flyers/{flyer}/photos', 
    'flyers.index': 'http://localhost/flyers', 
    'flyers.create': 'http://localhost/flyers/create', 
    'flyers.store': 'http://localhost/flyers', 
    'flyers.edit': 'http://localhost/flyers/{flyer}/edit', 
    'flyers.update': 'http://localhost/flyers/{flyer}', 
    'flyers.destroy': 'http://localhost/flyers/{flyer}', 
    'flyers.show': 'http://localhost/flyers/{zip}/{street}', 
    'login': 'http://localhost/login', 
    'logout': 'http://localhost/logout', 
    'register': 'http://localhost/register', 
    'password.request': 'http://localhost/password/reset', 
    'password.email': 'http://localhost/password/email', 
    'password.reset': 'http://localhost/password/reset/{token}', 
    'password.update': 'http://localhost/password/reset', 
    'home': 'http://localhost/home', 

 }; 
 export default routes